version: '3.8'

services:

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: product_api
      POSTGRES_PASSWORD: product_api
      POSTGRES_DB: products_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: products-api
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV
      - JWT_SECRET
      - DATABASE_URL
    depends_on:
      - db

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data: