version: '3.8'

services:

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: products-api
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - APP_NAME=${APP_NAME}
      - LOG_LEVEL_ENABLED=${LOG_LEVEL_ENABLED}
    depends_on:
      - db
      - redis

volumes:
  pg_data:
  redis_data: